import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Roger Kobs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt-BR'>
      <body
        className={`bg-zinc-900 leading-relaxed text-gray-400 antialiased ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
